//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirBNB_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews
    {
        public int ID { get; set; }
        public Nullable<int> Reservation_id { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Comment { get; set; }
    
        public virtual Reservation Reservation { get; set; }
    }
}
